/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  DelegateProposal,
  DelegateProposalInterface,
} from "../../../attack/Attacker02.sol/DelegateProposal";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "delegateCall",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class DelegateProposal__factory {
  static readonly abi = _abi;
  static createInterface(): DelegateProposalInterface {
    return new Interface(_abi) as DelegateProposalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): DelegateProposal {
    return new Contract(address, _abi, runner) as unknown as DelegateProposal;
  }
}
