/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Attacker02__factory } from "./Attacker02__factory";
export { DelegateProposal__factory } from "./DelegateProposal__factory";
