/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as attacker02Sol from "./Attacker02.sol";
export type { attacker02Sol };
export type { Attacker01 } from "./Attacker01";
export type { AttackerDefaultProposal } from "./AttackerDefaultProposal";
export type { AttackerMaliciousProposal } from "./AttackerMaliciousProposal";
